/**
 * Extract the set of class names a built stylesheet defines beneath the wrapper.
 *
 * Used to capture the Bootstrap 4 class surface before the Bootstrap 5 upgrade,
 * so the upgrade can be checked against a real baseline rather than a guess.
 *
 *   node scripts/extract-classes.ts [cssFile] [--out=file]
 *
 * Defaults to dist/css/bootstrap-grid.css and stdout.
 */

import { readFileSync, writeFileSync } from 'node:fs'

const WRAPPER = 'bootstrap-wrapper'

/**
 * Class names defined under `.bootstrap-wrapper` in `css`.
 *
 * Deliberately a regex rather than a full CSS parser: the input is generated by
 * Sass, so its selector shapes are predictable, and this keeps the script
 * dependency-free.
 */
export function extractClasses(css: string): string[] {
  const found = new Set<string>()

  // Strip comments and at-rule preludes so only selectors remain in play.
  const withoutComments = css.replace(/\/\*[\s\S]*?\*\//g, '')

  for (const match of withoutComments.matchAll(/\.bootstrap-wrapper\s+([^{]+)\{/g)) {
    const selectorList = match[1]
    if (!selectorList) continue

    for (const className of selectorList.matchAll(/\.([A-Za-z0-9_-]+)/g)) {
      const name = className[1]
      if (name && name !== WRAPPER) found.add(name)
    }
  }

  return [...found].sort((a, b) => a.localeCompare(b, 'en'))
}

const args = process.argv.slice(2)
const outFlag = args.find((a) => a.startsWith('--out='))
const input = args.find((a) => !a.startsWith('--')) ?? 'dist/css/bootstrap-grid.css'

const classes = extractClasses(readFileSync(input, 'utf8'))
const body = `${classes.join('\n')}\n`

if (outFlag) {
  const target = outFlag.slice('--out='.length)
  writeFileSync(target, body)
  console.log(`${classes.length} classes -> ${target}`)
} else {
  process.stdout.write(body)
}
